services:
  api:
    container_name: api
    image: rust:latest
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./api:/app
    command: cargo run
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    image: node:18-alpine
    working_dir: /app
    user: 1000:1000
    volumes:
      - ./frontend:/app
    command: ['sh', '-c', 'yarn install && yarn run dev']
    ports:
      - 1234:1234
    environment:
      API_URL: http://api:3000
      NEXT_PUBLIC_API_URL: http://localhost:3000
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:1234/crabfit
