name: API Checks

on:
  pull_request:
  push:
    branches:
      - main

# Fail on warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy
